
/****** Object:  Table [dbo].[USER_IMAGES]    Script Date: 6/23/2020 3:48:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USER_IMAGES](
	[UserImageID] [bigint] IDENTITY(1,1) NOT NULL,
	[UID] [bigint] NOT NULL,
	[PrimaryImage] [nchar](1) NOT NULL,
	[Image] [varbinary](max) NOT NULL,
	[FileName] [nvarchar](1000) NOT NULL,
	[ImageSize] [bigint] NOT NULL,
	[DateAdded] [datetime] NOT NULL,
 CONSTRAINT [PK_USER_IMAGES] PRIMARY KEY CLUSTERED 
(
	[UserImageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[USER_IMAGES] ADD  CONSTRAINT [DF_USER_IMAGES_UID]  DEFAULT ((0)) FOR [UID]
GO

ALTER TABLE [dbo].[USER_IMAGES] ADD  CONSTRAINT [DF_USER_IMAGES_PrimaryImage]  DEFAULT (N'N') FOR [PrimaryImage]
GO

ALTER TABLE [dbo].[USER_IMAGES] ADD  CONSTRAINT [DF_USER_IMAGES_FileName]  DEFAULT ('') FOR [FileName]
GO

ALTER TABLE [dbo].[USER_IMAGES] ADD  CONSTRAINT [DF_USER_IMAGES_ImageSize]  DEFAULT ((0)) FOR [ImageSize]
GO

ALTER TABLE [dbo].[USER_IMAGES] ADD  DEFAULT (getdate()) FOR [DateAdded]
GO


