
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EVENTS](
	[EventID] [bigint] IDENTITY(1,1) NOT NULL,
	[IsActive] [char](1) NOT NULL,
	[OwnerUID] [bigint] NOT NULL,
	[Title] [nvarchar](1000) NOT NULL,
	[Desc] [nvarchar](max) NOT NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[LocationTitle] [nvarchar](1000) NOT NULL,
	[LocationDesc] [nvarchar](max) NOT NULL,
	[Address1] [nvarchar](500) NOT NULL,
	[Address2] [nvarchar](500) NOT NULL,
	[City] [nvarchar](100) NOT NULL,
	[State] [nvarchar](100) NOT NULL,
	[Zip] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_EVENTS] PRIMARY KEY CLUSTERED 
(
	[EventID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_Enabled]  DEFAULT ('Y') FOR [IsActive]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_OwnerUID]  DEFAULT ((0)) FOR [OwnerUID]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_Title]  DEFAULT ('') FOR [Title]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_Desc]  DEFAULT ('') FOR [Desc]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_LocationName]  DEFAULT ('') FOR [LocationTitle]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_LocationDesc]  DEFAULT ('') FOR [LocationDesc]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_Address1]  DEFAULT ('') FOR [Address1]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_Address2]  DEFAULT ('') FOR [Address2]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_City]  DEFAULT ('') FOR [City]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_State]  DEFAULT ('') FOR [State]
GO

ALTER TABLE [dbo].[EVENTS] ADD  CONSTRAINT [DF_EVENTS_Zip]  DEFAULT ('') FOR [Zip]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EVENT_IMAGES](
	[EventImageID] [bigint] IDENTITY(1,1) NOT NULL,
	[EventID] [bigint] NOT NULL,
	[PrimaryImage] [nchar](1) NOT NULL,
	[Image] [varbinary](max) NOT NULL,
	[FileName] [nvarchar](1000) NOT NULL,
	[ImageSize] [bigint] NOT NULL,
	[DateAdded] [datetime] NOT NULL,
 CONSTRAINT [PK_EVENT_IMAGES] PRIMARY KEY CLUSTERED 
(
	[EventImageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[EVENT_IMAGES] ADD  CONSTRAINT [DF_EVENT_IMAGES_EventID]  DEFAULT ((0)) FOR [EventID]
GO

ALTER TABLE [dbo].[EVENT_IMAGES] ADD  CONSTRAINT [DF_EVENT_IMAGES_PrimaryImage]  DEFAULT (N'N') FOR [PrimaryImage]
GO

ALTER TABLE [dbo].[EVENT_IMAGES] ADD  CONSTRAINT [DF_EVENT_IMAGES_FileName]  DEFAULT ('') FOR [FileName]
GO

ALTER TABLE [dbo].[EVENT_IMAGES] ADD  CONSTRAINT [DF_EVENT_IMAGES_ImageSize]  DEFAULT ((0)) FOR [ImageSize]
GO

ALTER TABLE [dbo].[EVENT_IMAGES] ADD  DEFAULT (getdate()) FOR [DateAdded]
GO


